language: python
python:
- 2.7
- 3.3
install:
- python setup.py install
- pip install -r requirements.txt
script:
- python unit-tests.py
- coverage run --source=JustReleaseNotes unit-tests.py
after_success: coveralls
notifications:
  hipchat:
    rooms:
      secure: TKHX+xKwOT5aES1vOqeo6xvWrL2jN5X5OmAkV1E+8KwRKBsFUw/8PWSHeJlIBKFZ2ayu6NZQp3JVFJWy6dVT3cKNWDHqsqmJUPWFVTBFkptH5hmp8Tu8YmDKGF/7msxwKHkfH6uWqFCGCWpjhIXvFGGbJCO+dQXpvTRMStb/WEU=
