language: python
python:
  - 2.7
  - 3.3
install:
  - python setup.py install
  - pip install coveralls
script:
  - python tests/unit-tests.py
  - coverage run --source=JustReleaseNotes tests/unit-tests.py
after_success:
  coveralls