language: python
python:
  - 2.7
  - 3.3
install:
  - python setup.py install
  - pip install requests-mock
  - pip install coveralls
script:
  - python unit-tests.py
  - coverage run --source=JustReleaseNotes unit-tests.py
after_success:
  coveralls