language: python
python:
  - 2.7
  - 3.3
install:
  - pip install -r tests/requirements.txt
  - pip install coveralls
script:
  coverage run --source=JustReleaseNotes tests/unit-tests.py
after_success:
  coveralls